Update package.json
browserify/resolve pull request #248
Opened 2021-06-21 14:35 UTC by scastaldi

increase the minor version in order to get the latest change to path-parse

2021-06-21 15:47 UTC, ljharb requested changes
a) absolutely not, this is a patch increase, not a minor.
b) a release is unnecessary - path-parse is depended on with a semver range.

2021-06-21 15:48 UTC, ljharb commented
> It's already resolved in path-parse v1.0.7, and the `^` range means there's nothing that's needed here - just update it in your lockfile.
>
> Additionally, this was never a vulnerability for resolve itself; it's a false positive.

Duplicate of #246. Duplicate of #240. Duplicate of #243. Duplicate of #244. Duplicate of #246.

2021-06-21 15:48 UTC, closed without merging

2021-06-21 16:27 UTC, scastaldi commented
Hi,
My issue is the resolve package is in artifactory, and it is already in
1.20.0 so I guess it will not update unless I remove the node_modules, and
definitely updating the package-lock manually it should never be an option,
that's why I was thinking, increasing a minor version should be ok

this is my package-lock
"resolve": {
"version": "1.20.0",
"integrity": "sha1-YpoBP7P3B1XW8LeTXMHCxTeLGXU=",
"requires": {
"is-core-module": "^2.2.0",
"path-parse": "^1.0.6"
}
},


also, the reason I need to update path-parse is because there is a
vulnerability and I am getting flagged by Veracode, I already contacted the
team from appDynamics for the same issue and they were able to update their
package


Details
CVE-2021-23343
<http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-23343>

*Regular Expression Denial Of Service (ReDoS):* path-parse is vulnerable to
regular expression denial of service. An attacker is able to produce a
denial of service condition in the application through worst-case time
complexity via `splitDeviceRe`, `splitTailRe` and `splitPathRe`.

Please let me know what else I can do, other than editing package-lock (you
should never do) or removing/reading the package from artifactory (which I
have no rights)

Thanks,
Sebastian



On Mon, Jun 21, 2021 at 11:47 AM Jordan Harband ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> a) absolutely not, this is a patch increase, not a minor.
> b) a release is unnecessary - path-parse is depended on with a semver
> range.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/browserify/resolve/pull/248#pullrequestreview-688598655>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABNXFZJRZH32QG67LPOYX5DTT5NJ7ANCNFSM47BWZN2Q>
> .
>

2021-06-21 16:32 UTC, ljharb commented
You should be able to just reinstall resolve (or whatever transitively depends on it) and it will pull the latest version of path-parse.

You absolutely can manually edit package-lock - there's nothing wrong with that - but it shouldn't be necessary. Additionally, the package stored in artifactory already has `"path-parse": "^1.0.6"` so that should resolve to v1.0.7.

2021-06-21 16:39 UTC, scastaldi commented
in my local I removed package-lock.json and node_modules, but still does
not update to the latest path-parse. I think the reason is Artifactory does
not recognize the latest update because the version is the same, not really
sure what's the process for them to update, maybe they only update when
they see a new version

On Mon, Jun 21, 2021 at 12:32 PM Jordan Harband ***@***.***>
wrote:

> You should be able to just reinstall resolve (or whatever transitively
> depends on it) and it will pull the latest version of path-parse.
>
> You absolutely can manually edit package-lock - there's nothing wrong with
> that - but it shouldn't be necessary. Additionally, the package stored in
> artifactory already has "path-parse": "^1.0.6" so that should resolve to
> v1.0.7.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/browserify/resolve/pull/248#issuecomment-865178880>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABNXFZIYWEK573YK5ZIYM6DTT5SRLANCNFSM47BWZN2Q>
> .
>

2021-06-21 17:21 UTC, ljharb commented
That indeed sounds like a bug with Artifactory. I'd bet if you `npm install --no-save path-parse@1.0.7` tho (anywhere) that it would populate artifactory's cache, and then resolve's path-parse dependency will auto-update?

2021-06-24 14:13 UTC, scastaldi commented
Hi Jordan,
If you notice in npm, the npm package have not been updated in four month,
I think if you publish, then my issue will be fixed
https://www.npmjs.com/package/resolve
Last publish

4 months ago




On Mon, Jun 21, 2021 at 1:21 PM Jordan Harband ***@***.***>
wrote:

> That indeed sounds like a bug with Artifactory. I'd bet if you npm
> install --no-save ***@***.*** tho (anywhere) that it would populate
> artifactory's cache, and then resolve's path-parse dependency will
> auto-update?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/browserify/resolve/pull/248#issuecomment-865211306>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABNXFZKBOMPY5XUKF3SZBF3TT5YKTANCNFSM47BWZN2Q>
> .
>

2021-06-24 15:27 UTC, ljharb commented
@scastaldi youre correct, but i also don’t *need* to publish because a semver range means no issue exists. Just reinstall resolve (or whatever direct dep is transitively depending on it).

If that doesn’t work, it’s likely you’re using an internal registry that’s broken - try manually installing path-parse@1.0.7 anywhere to populate its cache, and then try to reinstall resolve again.

2021-06-24 17:42 UTC, scastaldi commented
I feel like a kid with divorce parents lol

Let me tell you the story:
I am not directly using resolve, I am using AppDynamics which uses resolve.
After asking them to update their references. Finally they were able to
update, but for some reason I still see the resolve issue with path-parse.
I contacted the guys from Artifactory and they said, there is nothing for
them to update, they said path-parse is at 1.0.7
Even if I npm install resolve it does not really update to 1.0.7. updating
package-lock is not an a good option because anyone that do an npm install
it will overwrite package-lock

so in reality I'm not sure why package-lock.json still showing 1.0.6 my
only guess is that you have not publish to npm, since the 1.0.7 was about a
month ago and npm shows Last publish
4 months ago

Any ideas?

On Thu, Jun 24, 2021 at 11:27 AM Jordan Harband ***@***.***>
wrote:

> @scastaldi <https://github.com/scastaldi> youre correct, but i also don’t
> *need* to publish because a semver range means no issue exists. Just
> reinstall resolve (or whatever direct dep is transitively depending on it).
>
> If that doesn’t work, it’s likely you’re using an internal registry that’s
> broken - try manually installing ***@***.*** anywhere to populate
> its cache, and then try to reinstall resolve again.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/browserify/resolve/pull/248#issuecomment-867731019>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABNXFZOYGKCRPLVKGMBU77LTUNFFZANCNFSM47BWZN2Q>
> .
>

2021-06-24 17:44 UTC, ljharb commented
I absolutely don't have to ever publish it to npm; the entire point of semver ranges is that this stuff is automatic.

What happens if you update package-lock, and commit that, and run `npm install`? My guess is that it won't overwrite it.